// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_pls_weights
arma::mat get_pls_weights(arma::mat X, arma::mat Y, String algorithm, const int xls_min_w, const int xls_max_w);
RcppExport SEXP _proximetricsR_get_pls_weights(SEXP XSEXP, SEXP YSEXP, SEXP algorithmSEXP, SEXP xls_min_wSEXP, SEXP xls_max_wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< String >::type algorithm(algorithmSEXP);
    Rcpp::traits::input_parameter< const int >::type xls_min_w(xls_min_wSEXP);
    Rcpp::traits::input_parameter< const int >::type xls_max_w(xls_max_wSEXP);
    rcpp_result_gen = Rcpp::wrap(get_pls_weights(X, Y, algorithm, xls_min_w, xls_max_w));
    return rcpp_result_gen;
END_RCPP
}
// estimate_basic_pls
List estimate_basic_pls(arma::mat X, arma::mat Y, List method);
RcppExport SEXP _proximetricsR_estimate_basic_pls(SEXP XSEXP, SEXP YSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_basic_pls(X, Y, method));
    return rcpp_result_gen;
END_RCPP
}
// estimate_all_pls
List estimate_all_pls(arma::mat X, arma::mat Y, List method);
RcppExport SEXP _proximetricsR_estimate_all_pls(SEXP XSEXP, SEXP YSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_all_pls(X, Y, method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_proximetricsR_get_pls_weights", (DL_FUNC) &_proximetricsR_get_pls_weights, 5},
    {"_proximetricsR_estimate_basic_pls", (DL_FUNC) &_proximetricsR_estimate_basic_pls, 3},
    {"_proximetricsR_estimate_all_pls", (DL_FUNC) &_proximetricsR_estimate_all_pls, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_proximetricsR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
